[tool.poetry]
name = "unic"
version = "0.4.1"
description = "Python package for converting various units."
authors = ["Subretu"]
maintainers = ["Subretu"]
license = "MIT"
readme = 'README.md'
repository = 'https://github.com/subretu/unic'
keywords = ['unit', 'convert', 'time', 'timestamp', 'length']

classifiers=[
    'License :: OSI Approved :: MIT License',

    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
]

[tool.poetry.dependencies]
python = "^3.8"
toml = "^0.10.2"
pydantic = "^2.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
mypy = "^1.4.1"
black = "^23.7.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
